### ISSUE TITLE
Authorization/authentications issues, spanish version: url statements, link to old documentation 

### ISSUE THREAD

**Issue by sarajoha** [DjangoGirls/tutorial-extensions#124]
Hi! I noticed a few issues in the **secure your website** section, in the Spanish version. They are: 

- Urls patterns not updated (using `url` statement instead of `path`)
- Login and logout urls use `views.login` instead of `views.LoginView.as_view()`
- There's a link to the documentation of Django's 1.10 version
- A sentence in the *Log in users* section, when asking to add a setting to `mysite/settings.py` is not very clear.

If it's okay, I'd like to volunteer to fix them.

**Comment by sarajoha** [comment]
Can I close this issue?

**Comment by das-g** [comment]
> Can I close this issue?

Have all problems raised by this issue been resolved by PR #125? If so, yes.

**Comment by sarajoha** [comment]
> > Can I close this issue?
> 
> Have all problems raised by this issue been resolved by PR #125? If so, yes.
Yes, they have. I'll close it then :)

**Comment by das-g** [comment]
By the way, you can add some text like "closes #124" to a commit message or the pull request description, and GitHub will close the issue automatically when the commit or PR is merged. [More info about this is available on help.github.com](https://help.github.com/en/articles/closing-issues-using-keywords).
