### ISSUE TITLE
Japanese translation

### ISSUE THREAD

**Issue by kaizumaki** [DjangoGirls/tutorial-extensions#126]
Hello. I am Kazuki, a coach of Django Girls Tokyo.
I would like to propose a merge for this pull request #123 .
As we have requested the merge last March #123, it has not been merged yet. Is there any problems? 

The women (and men)  who have finished the Django Girls Tutorial are going to try this extensions next.
Many people also need a Japanese translation.

This pull request #123 has been reviewed by Japanese people and I think it deserves what many people want.
Do you have any problems or concerns about merging?
If there is, I am willing to cooperate.

I am looking forward to it being merged.

**Comment by das-g** [comment]
I've merged that pull request now, despite not being able to judge it myself.

**Comment by kaizumaki** [comment]
@das-g Thank you for merging. We are very happy with this merge.
However, I found a link error and created a pull request again #128 .
