### ISSUE TITLE
I would like to translate this tutorial to Portuguese.

### ISSUE THREAD

**Issue by mjr** [DjangoGirls/tutorial-extensions#13]

**Comment by darlenedms** [comment]
Hi @manaiajunior 

Pyladies Brazil started to translate Django Girls manuals as you can see here: https://github.com/pyladies-brazil
Maybe you could help us :) https://github.com/pyladies-brazil/tutorial-extensions

**Comment by rapoulson** [comment]
Hi @manaiajunior! Our Portuguese translation is currently in beta mode and we'd be happy to have your help proofreading as we move towards official release. I've sent an invite to Crowdin, our translations tool to the email listed on your Github account. You can use Crowdin to vote for existing translations and suggest alternatives. For more info, please see our translation guidelines [translation guidelines] (http://translate.djangogirls.org/).

Thanks for volunteering! :fireworks: If you have any questions, don't hesitate to email the translations team at translations@djangogirls.org :confetti_ball:
