### ISSUE TITLE
discrepancy with initial tutorial

### ISSUE THREAD

**Issue by mroswell** [DjangoGirls/tutorial-extensions#17]
In https://github.com/DjangoGirls/tutorial-extensions/blob/master/homework/README.md

The Homework page says to look for:
```
        {% if post.published_date %}
                {{ post.published_date }}
        {% endif %}
```
But it actually contains:
 ```       {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% endif %}
```

**Comment by helenst** [comment]
It looks like the main tutorial was changed to bring this in line, so the two match. Thanks! I will close this now. :sparkles:
