### ISSUE TITLE
Section1: Incorrect HTML for Draft button

### ISSUE THREAD

**Issue by purplediane** [DjangoGirls/tutorial-extensions#26]
In the first Homework. The single/double quote nesting is incorrect. The HTML to insert is given as:

```html
<a href="{% url "post_draft_list" %}" class="top-menu"><span class="glyphicon glyphicon-edit"></span></a>
```
It should be:
```html
<a href="{% url 'post_draft_list' %}" class="top-menu"><span class="glyphicon glyphicon-edit"></span></a>
```

Also it should follow the link for the `post_new`, rather than be just above the `<h1><a href="/">Django Girls Blog</a></h1>` line, so that it will only display for an authorized user.

**Comment by purplediane** [comment]
The same double/single quote issue is in the HTML for the `blog/templates/blog/post_draft_list.html` file and the html for the publish and delete buttons. It seems to work ok, but I think technically it is still wrong. It certainly confuses the editor's text coloring.

**Comment by helenst** [comment]
I think this was fixed at some point as it appears to be correct now. I will close this now. Thank you! :cherry_blossom:

**Comment by purplediane** [comment]
Thanks!
