### ISSUE TITLE
How to translate - Django Girls tutorial-extensions?

### ISSUE THREAD

**Issue by faelaphoenix** [DjangoGirls/tutorial-extensions#30]
How do I translate the Django Girls tutorial-extensions? It does not appear in the list of items to be translated into crowdin.com.

**Comment by olasitarska** [comment]
Hi @faelaphoenix! Unfortunately, due to maintenance overhead on the translations, we're not able to offer Crowdin support for this. However, feel free to fork this repository and translate on Github!
