### ISSUE TITLE
Support for string view arguments to url() is deprecated

### ISSUE THREAD

**Issue by gVallverdu** [DjangoGirls/tutorial-extensions#35]
Hello,
Looking at this page : https://djangogirls.gitbooks.io/django-girls-tutorial-extensions/content/authentication_authorization/index.html#login-users

I got a warning such as  : 

```
RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got django.contrib.auth.views.login). Pass the callable instead.
url(r'^accounts/login/$', 'django.contrib.auth.views.login'),
```

Maybe you could change `urls.py` such as the following or any other more usual way : 

```python
from django.conf.urls import patterns, include, url
import django.contrib.auth.views as auth_views

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', auth_views.login, name="auth_views.login"),
    url(r'', include('blog.urls')),
)
```

Kinds

**Comment by KingaRitter** [comment]
Hi,

I also had issues at this point with the tutorial. First of all we realized that instead of 

`urlpatterns = patterns('',
.....
)`

one should use :
`urlpatterns=[
....
]`

but it doesn't fix the problem and I receive 
`RuntimeError: maximum recursion depth exceeded`

Kind regards

**Comment by helenst** [comment]
I think this has been fixed now. Thanks!
