### ISSUE TITLE
Secure your website - superfluous homework and typos

### ISSUE THREAD

**Issue by trueskawka** [DjangoGirls/tutorial-extensions#44]
I. Section _Improving the layout_ - homework: 

> Edit the template blog/templates/blog/post_detail.html to only show the edit buttons for authenticated users

is superfluous, as it was already done in the basic DjangoGirls tutorial (http://tutorial.djangogirls.org/en/django_forms/#security last code snippet)

II. A typo in _Login users_ second passage
is:

> In your mysite/urls.py add a url `url(r'^accounts/login/$', django.contrib.auth.views.login)`.

should be:

> In your mysite/urls.py add a url `url(r'^accounts/login/$', django.contrib.auth.views.login, name='login')`.

III. A typo in the second code snippet for _More on authenticated users_

is: `include django.contrib.auth.views`

should be: `import django.contrib.auth.views`

**Comment by helenst** [comment]
I. is still there in the "secure your website" section and should probably be removed
II. is OK now
III. is also OK now

Thanks! :sparkles:
