### ISSUE TITLE
"Patterns" and multiple discrepancies.

### ISSUE THREAD

**Issue by jorgeOmurillo** [DjangoGirls/tutorial-extensions#49]
In the _mysite/urls.py_, the code is completely different than how the Django Girls tutorial ends:

It looks like:

`from django.conf.urls import include, url`
`from django.contrib import admin`

`urlpatterns = [`
`url(r'^admin/', admin.site.urls),`
`url(r'', include('blog.urls')),`
`]`

The "Homework: secure your website" shows:

`from django.conf.urls import include, url`
`import django.contrib.auth.views`

`from django.contrib import admin`
`admin.autodiscover()`

`urlpatterns = patterns('',`
`url(r'^admin/', include(admin.site.urls)),`
`url(r'^accounts/login/$', django.contrib.auth.views.login, name='login'),`
`url(r'^accounts/logout/$', django.contrib.auth.views.logout, name='logout', kwargs={'next_page':` `'/'}),`
`url(r'', include('blog.urls')),`
`)`

When importing "patterns", Python throws an error that it is deprecated since v1.10.

**Comment by rege-django** [comment]
from django.conf.urls import include, url
from django.contrib.auth import views

from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/$', views.login, name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),
    url(r'',include('blog.urls')),
]

this works!

**Comment by helenst** [comment]
Thank you for pointing this out. The main tutorial was updated to Django 1.9 (which gives you this style of urls by default) but the extensions haven't been so it's out of sync now.

@rege-django we'd welcome a pull request if you would like to submit one (note that the `admin.autodiscover()` line can be taken out as Django no longer uses that) Thanks! :dolphin:
