### ISSUE TITLE
Problems with urls.py in 'Homework: create comment model' chapter

### ISSUE THREAD

**Issue by bellisk** [DjangoGirls/tutorial-extensions#54]
The tutorial says to add this pattern:

`url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),`

(1) It is not mentioned that you need to add the following import statement: `from blog import views`
(2) this assumes that the student hasn't completed the previous chapter, where they import `import django.contrib.auth.views`. (I suggested that my student amend this to `import django.contrib.auth.views as djangoviews` to avoid the conflict.)

**Comment by helenst** [comment]
Hi @bellisk - that pattern should be added to `blog/urls.py` (which at that point should already have `from . import views` to import all the blog views.

The auth views are only imported into the top level `urls.py` so there shouldn't be any naming conflict there (although I do think maybe it's clearer to give them a name like you did).

I'm going to close this - please feel free to reopen if you think something is still wrong there. Thank you! :sunflower:

**Comment by bellisk** [comment]
Ah, I see. Thanks for clearing that up, @helenst. :)
