### ISSUE TITLE
Allauth-Tutorial

### ISSUE THREAD

**Issue by muroshi** [DjangoGirls/tutorial-extensions#64]
Hello. I'd like to see an [allauth](https://github.com/pennersr/django-allauth)-tutorial. It's a rather big package with not very newbie friendly documentation.

**Comment by aniav** [comment]
Hey @muroshi, sorry for replying so late! I am happy you like to learn new things and you would like to learn allauth, but you need to create an issue on the allauth repo, we are not going to work on tutorial for this any time soon.
