### ISSUE TITLE
Update to Django 1.10

### ISSUE THREAD

**Issue by helenst** [DjangoGirls/tutorial-extensions#66]
The tutorial now works with Django 1.10 (https://github.com/DjangoGirls/tutorial/pull/946)

The extensions should be checked so that they also work with 1.10.

**Comment by supritashankar** [comment]
@helenst I would love to! Will complete migration to other locales and then jump onto this.

**Comment by faheel** [comment]
I've checked that the extensions do not mention any version number, nor do they contain any function/property that was deprecated in Django 1.10. So this issue can be closed.

**Comment by aniav** [comment]
This has already been implemented, thank you! 🎉
