### ISSUE TITLE
include(admin.site.urls) is changed in Django 1.10

### ISSUE THREAD

**Issue by sagayev** [DjangoGirls/tutorial-extensions#75]
__include__ function is not needed in Django 1.10 in url.py

**https://djangogirls.gitbooks.io/django-girls-tutorial-extensions/authentication_authorization/**

urlpatterns = [
    url(r'^admin/', **include(admin.site.urls)**),]

**https://docs.djangoproject.com/en/1.10/ref/contrib/admin/**
# urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]
**Changed in Django 1.9:
In previous versions, you would pass admin.site.urls to include().**

**Comment by pxlotus** [comment]
well mine is using 'PATH' instead of 'url': how am i to go about that?
           """from django.contrib import admin
              from django.urls import path

               urlpatterns = [
               path('admin/', admin.site.urls),
	       path('webapp/', include('webapp.urls'))"""

 it's causing me alot of errors: like,
            """from django.contrib import admin, include
ImportError: cannot import name 'include'"""

**Comment by magul** [comment]
Hi @pxlotus,

first of all for support regarding tutorial You can ask (and get quickier response) on Gitter room: https://gitter.im/DjangoGirls/tutorial

And regarding `path` - it looks that' You are trying to use Django 2.0, which is not yet supported by Django Girls tutorial.
