### ISSUE TITLE
Two minor documentation bugs

### ISSUE THREAD

**Issue by abhishek-nigam** [DjangoGirls/tutorial-extensions#79]
- In the 'Log in users' section, just before the first code snippet, "In your mysite/urls.py add a url url(r'^accounts/login/$', views.login). So the file should now look similar to this: " should be changed to "In your mysite/urls.py add a url url(r'^accounts/login/$', views.login, name='login'). So the file should now look similar to this:" ~ adding name='login' in the url statement

- In the homework given in 'Improving the layout' section, it should be "delete and edit buttons" instead of "add and delete buttons", as we have already taken care of the add button in base.html as mentioned in the code snippet in the same section.

**Comment by helenst** [comment]
Hi @abhishek-nigam - thank you for adding these! Please could you move one of these to a separate issue? Keeping them in separate issues will make it easier for somebody to pick up either one or the other.

**Comment by aniav** [comment]
It's now fixed :)
