### ISSUE TITLE
Typo in Url in Section "Add publish button"

### ISSUE THREAD

**Issue by lusy** [DjangoGirls/tutorial-extensions#85]
Hey, I think in the "Add publish button" section the url should read `blog/templates/blog/post_detail.html`, that is, with templateS in plural, instead of singular as it is now..

**Comment by AnkurBegining** [comment]
Yaa same issue.

**Comment by aniav** [comment]
Fixed that in c4d59020806ccc41a0c2c46727b0cf54f00e91bc. Thanks for noticing that! :)
