### ISSUE TITLE
If there is only one choice, don't ask the user to choose

### ISSUE THREAD

**Issue by jonkiparsky** [DjangoGirls/tutorial-extensions#93]
A user visiting https://djangogirls.gitbooks.io/django-girls-tutorial-extensions/ is asked to select from one available option (English). If there's only one choice, just take me there!

**Comment by aniav** [comment]
@jonkiparsky It seems that is no longer an issue, but that's also how gitbook works when you decide to support multiple languages in the structure and allow for people to add pull requests :)
