### ISSUE TITLE
Proposal: add a tutorial extension based on Wagtail

### ISSUE THREAD

**Issue by thibaudcolas** [DjangoGirls/tutorial-extensions#96]
Hi 👋 

I've been thinking about writing a beginner-level tutorial for [Wagtail](https://wagtail.io/), a popular CMS based on Django. Would this be interesting as a new extension? I'm willing to make that happen but I would like to check first whether others think it makes sense. 

It is very common for people to initially start a project with Django, then bring on Wagtail later on to manage their site's content – it comes with its own admin interface which is generally more user-friendly than Django's (I help build it so I'm biased), as well as features specific to content management. Here are my ideas for what could go in the extension:

- Explaining what Wagtail is, what a CMS is, how this fits with Django.
- Installing Wagtail in the existing project.
- Creating a page model, reflecting on how this compares with Django.
- Creating a contact form on the site (very easy).
- Creating a basic image gallery? (Wagtail does lots around this so that's not much code).

I think those things would be a good mix of being interesting to do and also simple enough for the extension to not be too long, but I'll check with other Wagtail people if they have more ideas.

How does that sound?

**Comment by aniav** [comment]
Sorry for not replying any time earlier. Go ahead if you still want to add anything like that!  🎉

**Comment by thibaudcolas** [comment]
@aniav no worries, thank you for the encouragement 🙂

 I got good feedback from the Wagtail community about the idea, and Twitter seems enthusiastic too (https://twitter.com/thibaud_colas/status/933808772371374080), so I'm very keen to make this happen.

... and I also found more people to help! (cc @codiebeulaine, @LisaAdamsPRK, @tomdyson, @jjanssen, @tonyyates)

Will keep you posted :)

**Comment by thibaudcolas** [comment]
For anyone interested in this – I haven’t found much time to make this happen, but did write a first page for the tutorial, to cover the initial setup: https://github.com/thibaudcolas/wagtail-tutorials/tree/master/en/django_girls_extension_getting_started_with_wagtail

Anyone wanting to make this happen is very welcome to reuse any of this.

**Comment by thibaudcolas** [comment]
Just a quick note to say @amakarudze and I discussed this today, and it seems like we have a plan :) We’ll either keep working on the draft I started in 2020, or create the extension based on the [Google Season of Docs tutorials project](https://wagtail.org/blog/our-first-google-season-of-docs-2023/) currently happening with Wagtail.
